/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OldindexImport } from './routes/old_index'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const OldindexRoute = OldindexImport.update({
  id: '/old_index',
  path: '/old_index',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/old_index': {
      id: '/old_index'
      path: '/old_index'
      fullPath: '/old_index'
      preLoaderRoute: typeof OldindexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/old_index': typeof OldindexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/old_index': typeof OldindexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/old_index': typeof OldindexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/old_index'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/old_index'
  id: '__root__' | '/' | '/old_index'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OldindexRoute: typeof OldindexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OldindexRoute: OldindexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/old_index"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/old_index": {
      "filePath": "old_index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
